In [ ]:
#1.	Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
#tek boyutlu dizilere vektor,Birden fazlaboyutlu dizilere matris denir

In [33]:
#2. 10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np
liste=[1,2,3,4,5,6,7,8,9,0]
array=np.array(liste)
print(liste,type(liste))
print(array,type(array))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0] <class 'list'>
[1 2 3 4 5 6 7 8 9 0] <class 'numpy.ndarray'>


In [9]:
#3.	Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
zeros=np.zeros((10,10),dtype="int32")
zeros


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
#4.	Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
ones=np.ones((10,10))
ones


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
#5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
number=np.full((10,10),9,dtype="int32")
number

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [15]:
#6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
range=np.arange(5,25,3)
range

array([ 5,  8, 11, 14, 17, 20, 23])

In [16]:
#7.	-1 ile 1 arasinda 30 adet Array olusturunuz.
lins=np.linspace(-1,1,30)
lins

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [18]:
#8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.
shape=np.arange(0,30).reshape(5,6)
shape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [20]:
#9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 
dioganel=np.eye(10,10)
dioganel


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
#10.	0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
#a.	eleman sayisini
#b.	boyut bilgisini/sayisini
#c.	satir X sutun bilgisini
#d.	veri tipini numpy metodlariyla yazdiriniz



numbers=np.random.randint(0,10 ,(5,10))
print(numbers)
print("size ",numbers.size)
print("shape",numbers.shape)
print("dimensions ",numbers.ndim)
print("dtype ",numbers.dtype)


[[3 9 2 2 3 4 5 0 8 4]
 [2 3 8 2 5 0 1 3 4 3]
 [5 3 6 0 8 3 7 3 5 7]
 [0 3 6 7 7 9 2 8 2 8]
 [5 2 4 7 3 5 1 0 7 9]]
size  50
shape (5, 10)
dimensions  2
dtype  int32
<class 'numpy.ndarray'>


In [31]:
#11.	0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. 
#(3 boyutlu bir matris olusturulacak) 
randnum=np.random.randint(0,10 ,(3,4,7))#(adet,satir,sutun)
randnum



array([[[2, 4, 1, 7, 9, 2, 0],
        [5, 3, 5, 8, 9, 8, 6],
        [7, 6, 3, 2, 0, 6, 7],
        [5, 5, 4, 7, 8, 6, 0]],

       [[6, 0, 7, 4, 5, 6, 6],
        [9, 6, 3, 3, 8, 3, 0],
        [1, 5, 2, 4, 5, 8, 2],
        [5, 3, 9, 9, 4, 7, 2]],

       [[5, 1, 6, 6, 8, 8, 8],
        [4, 2, 4, 7, 5, 7, 3],
        [1, 2, 0, 8, 3, 4, 2],
        [7, 1, 7, 1, 1, 5, 6]]])

In [42]:
#12.	Bir vektor olusturunuz ve daha sonrasinda
#ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
vector=np.arange(10)
print(vector)
matris=vector.reshape(2,5)

print(matris)




[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [117]:
#13.	4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
x=np.arange(10)
y=np.arange(10,20)
z=np.arange(20,30)
t=np.arange(30,40)

sum_array=np.hstack((x,y,z,t))
sum_array2=np.concatenate([x,y,z,t])
print("x")
print(x)
print("y")
print(y)
print("z")
print(z)
print("t")
print(t)
print("sum_array")
print(sum_array)
print("sum_array2")
print(sum_array2)


x
[0 1 2 3 4 5 6 7 8 9]
y
[10 11 12 13 14 15 16 17 18 19]
z
[20 21 22 23 24 25 26 27 28 29]
t
[30 31 32 33 34 35 36 37 38 39]
sum_array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
sum_array2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [29]:
#14.	2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), 
#bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,
x=np.array([[1,2,3,4]])
y=np.array([[6,7,8,9],[10,22,33,44]])
x_y=np.concatenate([x,y])

print("x")
print(x)
print("y")
print(y)
print("x_y")
print(x_y)





x
[[1 2 3 4]]
y
[[ 6  7  8  9]
 [10 22 33 44]]
x_y
[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 22 33 44]]


In [13]:
#15.	Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?
print("""
axis=1 ,satir islemleri
axis=0 ,sutun islemlerini belirtir
""")



axis=1 ,satir islemleri
axis=0 ,sutun islemlerini belirtir



In [14]:
#16.	Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

#dikkat satir birlestirmelerde satir sayilari esit olmali
x_row=np.random.randint(1,11,(3,8,))
y_row=np.random.randint(1,11,(3,7))
rowx_y=np.hstack((x_row,y_row))

#dikkat sutun birlestirmelerde sutun sayilari esit olmali
x_col=np.random.randint(1,11,(4,8,))
y_col=np.random.randint(1,11,(2,8))
colx_y=np.vstack((x_col,y_col))

print("row ")
print(rowx_y)
print("col")
print(colx_y)


row 
[[ 6  1 10  1  9  3 10  5  7  8 10  1 10  7  2]
 [ 7  9  9  4  3 10  7  8  9 10  7  7  3  6  1]
 [ 7  1  2  8  3  7 10  2 10  6  3  1  8  8  4]]
col
[[ 7  5  2 10  2  3  5 10]
 [ 2  8  4  6  1  4  8  8]
 [ 8  4 10  1  5  5  5  1]
 [ 6  3  3 10  8  4  5  4]
 [ 2  2  6  7  1  3  9 10]
 [ 9  5  8  4  5  3  5  9]]


In [30]:
#17.	10 elemanli bi liste olusturunuz ve
#bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.
liste=list(range(32))
print(liste)

a,b,c,d=np.split(liste,[7,15,26])
print("a")
print(a)
print("b")
print(b)
print("c")
print(c)
print("d")
print(d)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
a
[0 1 2 3 4 5 6]
b
[ 7  8  9 10 11 12 13 14]
c
[15 16 17 18 19 20 21 22 23 24 25]
d
[26 27 28 29 30 31]


In [63]:
#18.	Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.
#Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

array=np.random.randint(0,100,size=15)
print(array)
sort_array=np.sort(array)
print(sort_array)
for i in range(len(sort_array)):
    print(i+1,"=",sort_array[i])
   
   
 

[87 60 12 92 34 39 19 28 34 65 48 46 56 29 80]
[12 19 28 29 34 34 39 46 48 56 60 65 80 87 92]
1 = 12
2 = 19
3 = 28
4 = 29
5 = 34
6 = 34
7 = 39
8 = 46
9 = 48
10 = 56
11 = 60
12 = 65
13 = 80
14 = 87
15 = 92


In [64]:


#19.	20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin
numbers=np.random.randint(20,size=20)
print(numbers)
print(numbers[3])
print(numbers[5])
print(numbers[7])

[ 0  9  3  1 15  3 16  7 16  7 14 18 16  0  9  6  4  6 17  3]
1
3
7


In [18]:
#20.	10 elemanli random bir vektor olusturunuz ve bu arrayin 
#4. elemanini farkli bir sayiyla degistiriniz.
numbers=np.random.randint(20,size=10)
print(numbers)
numbers[4]=44
print("change")
print(numbers)


[ 3  0 19 13 19  6 11 16  4  8]
change
[ 3  0 19 13 44  6 11 16  4  8]


In [19]:
#21.	“Diagonal Matrix” ve “Trace Matrix” 
#kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

print("""
dioganal matris= nxn bir matriste (a[0,0] --> a[n,n] )indexindeki kosegeni olusturan 
sayilar sifirdan farkli ve diger indexteki sayilar 0 ise bu matrise dioganal matris denir. 

""")

Print("""
Trace Matrix: nxn bir matrisin (a[0,0] --> a[n,n] )kosegenini olusturan sayilarin toplamina Trace denir.
toplam=a[0,0]+a[1,1]+........+a[n,n] toplami ile ifade edilir
""")




In [15]:
#22.	5x5’lik Diagonal bir matris olusturunuz ve 
#Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

dioganal=np.arange(1,26).reshape(5,5)
print(np.diag(np.diag(dioganal)))
for i in range(len(dioganal)):
    print(dioganal[i,i])

[[ 1  0  0  0  0]
 [ 0  7  0  0  0]
 [ 0  0 13  0  0]
 [ 0  0  0 19  0]
 [ 0  0  0  0 25]]
1
7
13
19
25


In [11]:
#23. 10 ile 20 arasinda bir vektor olusturunuz. 
#Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

index=np.arange(10,20)
print(index)

print(index[3:10])


[10 11 12 13 14 15 16 17 18 19]
[13 14 15 16 17 18 19]


In [57]:
#24. 10X10 luk bir matris olusturunuz ve ;
matris=np.arange(1,101).reshape(10,10)
print(matris,'\n')
# . 3.satir ve 5.sutuna ulasiniz.

print(matris[3,])
print(matris[:,4])
print("a. 5.sutunun tum satirlarina ulasiniz.")
print(matris[:,4])
print("b. Tum sutunlarin 2.satirlarina ulasiniz.")
print(matris[1,])
print(" c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.")
print(matris[1:6],)
print("d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.")
print(matris[2:5,3:7])
print("e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.")
print(matris[5:-1,:4])
print("f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.")
print(matris[:,3:10:3])
print("g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.")
matris[5,5:6]=1981
print(matris)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 

[31 32 33 34 35 36 37 38 39 40]
[ 5 15 25 35 45 55 65 75 85 95]
a. 5.sutunun tum satirlarina ulasiniz.
[ 5 15 25 35 45 55 65 75 85 95]
b. Tum sutunlarin 2.satirlarina ulasiniz.
[11 12 13 14 15 16 17 18 19 20]
 c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]
d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
[[24 25 26 27]
 [34 35 36 37]
 [44 45 46 47]]
e.

In [66]:
# 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu)
#ve numpy metodlariyla asagidaki islemleri uygulayin;

array=np.arange(0,50,5)
print(array)
print("20 den buyuk olan kac deger var.")
print(np.sum(array>20))
print("a. 30’dan kucuk kac deger var")
print(np.sum(array<30))
print("b. icerisinde 33 gecen kac deger var")
print(np.sum(array==33))
print("c. olusturulan arrayin tum elemanlarini 5 ile carpin.")
print(array*5)
print("d. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.")
print(array %2)


[ 0  5 10 15 20 25 30 35 40 45]
20 den buyuk olan kac deger var.
5
a. 30’dan kucuk kac deger var
6
b. icerisinde 33 gecen kac deger var
0
c. olusturulan arrayin tum elemanlarini 5 ile carpin.
[  0  25  50  75 100 125 150 175 200 225]
d. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
[0 1 0 1 0 1 0 1 0 1]


In [71]:
# 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
array=np.linspace(0,1,50)
print(array)
print(" ortamasini aliniz.")
print(array.mean())
print("a. standart sapmasini aliniz.")
print(array.std())
print("b. varyansini aliniz")
print(array.var())
print("c. median’ini aliniz.")
print(np.median(array))
print("d. en kucuk degeri bulunuz.")
print(array.min())
print("e. en buyuk degeri bulunuz.")
print(array.max())

 

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
 orlamasini aliniz.
0.5
a. standart sapmasini aliniz.
0.2945075446869757
b. varyansini aliniz
0.086734693877551
c. median’ini aliniz.
0.5
d. en kucuk degeri bulunuz.
0.0
e. en buyuk degeri bulunuz.
1.0
